### ISSUE TITLE
Add ability to update versions in `mypy` hook's `additional_dependencies`

### ISSUE THREAD

**Issue by macintacos** [GabDug/sync-pre-commit-lock#24]
This plugin is great, thanks for making it!

One thing that would put it over the top for me would be to add the ability to update `mypy`'s `additional_dependencies` array to match the versions in the lock file as well. Any chance this could be something that is added to this plugin? It feels like a natural extension of this project.

**Comment by GabDug** [comment]
Hey @macintacos!

This is indeed a natural extension of the project, and was already an area of improvement.

For a first version, I think I'll just go through `additional_dependencies` of all hooks, and update all requirements to be the exact pinned version of the package. 
In the future, we may want to map PDM/Poetry dependency group to a hook's `additional_dependencies`, so that addition and deletion of packages are handled as well.

I don't use the mypy hook or `additional_dependencies`, would you mind sharing one of your configuration as a test case?
